package engine

import (
	"fmt"
	"strings"

	"github.com/stackrail/incident-investigator/internal/model"
)

// ReportGenerator assembles the final investigation deliverable.
type ReportGenerator interface {
	Generate(s *model.Session, sig Signals) model.Report
}

// HeuristicReportGenerator builds an executive summary, recommendations and a
// markdown postmortem from the session state.
type HeuristicReportGenerator struct{}

// NewHeuristicReportGenerator returns the default generator.
func NewHeuristicReportGenerator() *HeuristicReportGenerator { return &HeuristicReportGenerator{} }

// recommendationsByHypothesis maps a hypothesis id to concrete follow-ups.
var recommendationsByHypothesis = map[string][]string{
	"hypothesis-deployment-caused": {
		"Roll back the suspect deployment and confirm recovery.",
		"Add canary/progressive delivery and automated rollback gates.",
	},
	"hypothesis-database-saturation": {
		"Investigate database capacity, slow queries and connection-pool limits.",
		"Add circuit breakers and backpressure to protect the database.",
	},
	"hypothesis-configuration-change": {
		"Audit the recent configuration/feature-flag change and revert if needed.",
		"Add configuration validation and staged rollout in CI/CD.",
	},
	"hypothesis-network-dns": {
		"Verify DNS resolvers and network paths; add synthetic connectivity checks.",
		"Implement resilient retries with jittered backoff for transient failures.",
	},
	"hypothesis-certificate-expiry": {
		"Renew the affected certificate and automate renewal (e.g. ACME).",
		"Add certificate-expiry alerting well ahead of expiry.",
	},
	"hypothesis-resource-exhaustion": {
		"Right-size memory/CPU limits and investigate the suspected leak.",
		"Enable autoscaling and add saturation alerts.",
	},
	"hypothesis-retry-storm": {
		"Introduce retry budgets, jittered backoff and circuit breakers.",
		"Add load-shedding to prevent cascading amplification.",
	},
}

// Generate implements ReportGenerator.
func (g *HeuristicReportGenerator) Generate(s *model.Session, sig Signals) model.Report {
	report := model.Report{
		SessionID:       s.ID,
		Question:        s.Question,
		Timeline:        s.Timeline,
		Evidence:        s.Evidence,
		Hypotheses:      s.Hypotheses,
		Graph:           s.Graph,
		BlastRadius:     s.BlastRadius,
		Contradictions:  s.Contradictions,
		MissingEvidence: s.MissingEvidence,
		Confidence:      s.Confidence,
	}

	report.RootCauseCandidates = topCandidates(s.Hypotheses, 3)
	report.ExecutiveSummary = g.executiveSummary(s)
	report.Recommendations = g.recommendations(s)
	report.Postmortem = g.postmortem(s, report)

	return report
}

func topCandidates(hs []model.Hypothesis, n int) []model.Hypothesis {
	out := make([]model.Hypothesis, 0, n)
	for _, h := range hs {
		if h.Status == model.StatusRefuted {
			continue
		}
		out = append(out, h)
		if len(out) >= n {
			break
		}
	}
	return out
}

func (g *HeuristicReportGenerator) executiveSummary(s *model.Session) string {
	if len(s.Hypotheses) == 0 {
		return "No evidence has been submitted yet; no conclusion can be drawn."
	}
	lead := s.Hypotheses[0]
	var b strings.Builder
	fmt.Fprintf(&b, "Investigating: %q.", s.Question)
	fmt.Fprintf(&b, " Leading explanation (%.0f%% relative likelihood): %s",
		lead.Confidence, lead.Statement)
	fmt.Fprintf(&b, " Overall investigation confidence is %.0f%% based on %d evidence item(s) across %d categor(y/ies).",
		s.Confidence, len(s.Evidence), countCategories(s))
	if len(s.Contradictions) > 0 {
		fmt.Fprintf(&b, " Note: %d contradiction(s) were detected and should be resolved.", len(s.Contradictions))
	}
	if len(s.MissingEvidence) > 0 {
		fmt.Fprintf(&b, " %d additional evidence categor(y/ies) would strengthen the conclusion.", len(s.MissingEvidence))
	}
	return b.String()
}

func (g *HeuristicReportGenerator) recommendations(s *model.Session) []string {
	var recs []string
	if len(s.Hypotheses) > 0 {
		lead := s.Hypotheses[0]
		recs = append(recs, recommendationsByHypothesis[lead.ID]...)
	}
	if len(s.MissingEvidence) > 0 {
		cats := make([]string, 0, len(s.MissingEvidence))
		for _, m := range s.MissingEvidence {
			cats = append(cats, string(m.Category))
		}
		recs = append(recs, "Collect missing evidence to raise confidence: "+strings.Join(cats, ", ")+".")
	}
	if len(s.Contradictions) > 0 {
		recs = append(recs, "Resolve the detected contradictions before finalizing the root cause.")
	}
	if len(recs) == 0 {
		recs = append(recs, "Continue monitoring; no specific remediation is indicated by current evidence.")
	}
	return recs
}

func (g *HeuristicReportGenerator) postmortem(s *model.Session, r model.Report) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Postmortem: %s\n\n", s.Question)
	fmt.Fprintf(&b, "_Generated by Incident Investigator. Confidence: %.0f%%._\n\n", s.Confidence)

	b.WriteString("## Executive Summary\n\n")
	b.WriteString(r.ExecutiveSummary + "\n\n")

	b.WriteString("## Timeline\n\n")
	if len(s.Timeline) == 0 {
		b.WriteString("_No timeline could be reconstructed._\n\n")
	} else {
		for _, e := range s.Timeline {
			fmt.Fprintf(&b, "- **%s** [%s] %s\n", e.Timestamp.Format("15:04:05"), e.Category, e.Description)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Root Cause Candidates\n\n")
	for _, h := range r.RootCauseCandidates {
		fmt.Fprintf(&b, "- **%s** — %.0f%% (%s)\n", h.Statement, h.Confidence, h.Status)
	}
	b.WriteString("\n")

	if len(s.Contradictions) > 0 {
		b.WriteString("## Contradictions\n\n")
		for _, c := range s.Contradictions {
			fmt.Fprintf(&b, "- [%s] %s\n", c.Severity, c.Description)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Blast Radius\n\n")
	writeScoped(&b, "Services", s.BlastRadius.Services)
	writeScoped(&b, "Regions", s.BlastRadius.Regions)
	writeScoped(&b, "Customers", s.BlastRadius.Customers)
	writeScoped(&b, "APIs", s.BlastRadius.APIs)
	b.WriteString("\n")

	if len(s.MissingEvidence) > 0 {
		b.WriteString("## Missing Evidence\n\n")
		for _, m := range s.MissingEvidence {
			fmt.Fprintf(&b, "- %s (%s): %s\n", m.Category, m.Priority, m.Reason)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Recommendations\n\n")
	for _, rec := range r.Recommendations {
		fmt.Fprintf(&b, "- %s\n", rec)
	}

	return b.String()
}

func writeScoped(b *strings.Builder, title string, items []model.ScopedItem) {
	if len(items) == 0 {
		return
	}
	fmt.Fprintf(b, "**%s:** ", title)
	parts := make([]string, 0, len(items))
	for _, it := range items {
		parts = append(parts, fmt.Sprintf("%s (%.0f%%)", it.Name, it.Confidence))
	}
	b.WriteString(strings.Join(parts, ", ") + "\n\n")
}

func countCategories(s *model.Session) int {
	set := map[model.Category]bool{}
	for _, e := range s.Evidence {
		set[e.Category] = true
	}
	return len(set)
}
